version: '3'

services:
  db:
    build: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=saltedandhashed
      - POSTGRES_DB=postgres
    restart: always

  server:
    build: ./server
    ports: 
      - "8080:8080"
    environment:
      - DB_CONN=user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} host=db port=5432 dbname=${POSTGRES_DB}
    restart: always